name: Build Alpine

on:
  push:
    branches:
      - main
    paths:
      - "alpine/**"
      - ".github/workflows/alpine.yaml"
      - "install_tooling.sh"
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_REPO: lusu007/devpsace-containers/alpine

defaults:
  run:
    working-directory: alpine

jobs:
  alpine:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: 3
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: loft-sh/setup-devspace@main
      - run: devspace build --var TAG=${{ matrix.tag }}
